<?php
/**
 * @file
 * Code for the Feature News feature.
 */

include_once 'feature_news.features.inc';
/**
 * Title and image are link to the node or to the field_news_url_target field
 * Working directly on the "title" field was not possible because of the automatic
 * format which is not html (tag are not interpreted). So I decided to work on the 
 * "news_url_target" field
 */
function feature_news_views_pre_render(&$view) {
	//dpm($view->name);
  //dpm($view->current_display);
       if (($view->name == 'news' && $view->current_display == 'page') || ($view->name == 'news' && $view->current_display == 'block_1')) {
            foreach ($view->result as &$value) {
              
//Test if an url target is specified 
              if (sizeof($value->field_field_news_url_target) > 0) {
                  
                  $begin_http = preg_match("#^http|https(.*)$#i", $value->field_field_news_url_target[0]['rendered']['#markup']);                
                  $custom_url = $begin_http ? $value->field_field_news_url_target[0]['rendered']['#markup'] : 'http://'.$value->field_field_news_url_target[0]['rendered']['#markup'];                   
                  $target = (empty($value->field_field_news_new_window) || !$value->field_field_news_new_window[0]['raw']['value'])? '' : ' target="_blank" ';
                  if (sizeof($value->field_field_news_image) > 0) {
                    $value->field_field_news_image[0]['rendered']['#markup'] = '<a '.$target.' href="'.$custom_url.'">'.$value->field_field_news_image[0]['rendered']['#markup'].'</a>';
                  }
                  $value->field_field_news_url_target[0]['rendered']['#markup'] = '<h3 class="title-news-list"><a '.$target.' href="'.$custom_url.'">'.$value->node_title.'</a></h3>';
                }else {
                  $href = ' href="'.drupal_get_path_alias("node/".$value->nid).'" ';
                  $value->field_field_news_url_target[0]['rendered']['#markup'] = '<h3 class="title-news-list"><a href="/node/'.$value->nid.'">'.$value->node_title.'</a></h3>';
                  if (sizeof($value->field_field_news_image) > 0) {
                    $value->field_field_news_image[0]['rendered']['#markup'] = '<a '.$href.'>'.$value->field_field_news_image[0]['rendered']['#markup'].'</a>';
                  }
                }
            }
		
	}
}

